# Generated by Django 2.2.3 on 2019-07-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255, unique=True)),
                ('password', models.CharField(default='', max_length=500)),
                ('display_name', models.CharField(default='', max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Role')),
            ],
        ),
    ]
